spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ostock_dev
    username: postgres
    password: "{cipher}fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
management:
  endpoints:
    web:
      exposure:
        include: "*"